### PR TITLE
to merge Hangman

### PR DESCRIPTION
**Pull request by clock21am**

### CODE REVIEW

**Comment by bdoin** [comment]
When I loose I have the bad bonus and the word is displayed but there is not normal way to go to the next word. Clicking on a char append it and go to the next word but this is not the best way.

When I click on the config button nothing happens and GCompris becomes locked. Can't do anything more.

**Comment by clock21am** [comment]
about the bad bonus and the word display after the is for the kid to know what is the correct answer for this question 
and about the GCompris lock it is not locking in my system now yes but it did lock in my system for the frist time i build after rebasing 
should i not display the word after wrong trials ?

**Comment by bdoin** [comment]
Yes, you should display the word but you should provide perhaps an OK button to move to the next word.

**Comment by clock21am** [comment]
okay button is done and config freezing is also done :)

**Pull request closed without merging**
