### PR TITLE
Exercise

### PR DESCRIPTION
**Pull request by clock21am**
Hangman activity completed

### CODE REVIEW

**Comment by bdoin** [comment]
you have to rebase your work on the master branch first to le me check and merge your work.

**Comment by clock21am** [comment]
Hi Bruno ,

Actually I am having internet problem in my college as soon as the internet
come i will rebase my work .

But do I need to rebase my master and then merge my exercise branch to my
master then I should make a pull request ?
Actually I am bit confused about how how to make pull request.

Regards,
Rajdeep.

**Comment by bdoin** [comment]
the best practice if to keep the master branch of your clone a copy of the official repository and have a branch for each work (like hangman). 
Then you keep you master branch up to date by rebasing it on the upstream master branch.
And you rebase your hangman branch on your master branch.
Then you are ready to make a pull request of the hangman branch.

**Comment by bdoin** [comment]
I tried your activity, As it is, it is more a typing activity from a given voice than a hangman. In a hangman, you give a clue and the children must find letters. You can how the image and play the voice at the end but not up front or you miss thhe hangman game play.

**Pull request closed without merging**
